version: "3.9"
services:
  app:
    container_name: app
    build: ./app
    environment:
      PG_DB: ${PG_DB}
      PG_USER: ${PG_USER}
      PG_PASSWORD: ${PG_PASSWORD}
    expose:
      - 5000
    depends_on:
      - db
    networks:
      - app_network

  db:
    container_name: postgres
    image: postgres:13.0-alpine
    environment:
      POSTGRES_DB: ${PG_DB}
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      PGDATA: "/var/lib/postgresql/data/pgdata"
    volumes:
      - data_db:/var/lib/postgresql/data
    expose:
      - 5432
    restart: unless-stopped
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    networks:
      - app_network

  nginx:
    container_name: nginx
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - app
    networks:
      - app_network

#  pgadmin:
#    image: dpage/pgadmin4
#    container_name: pgadmin4
#    restart: always
#    environment:
#      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
#      - PGADMIN_DEFAULT_PASSWORD=admin
#    ports:
#      - "8080:80"
#    networks:
#      - app_network

volumes:
  data_db:

networks:
  app_network:
    driver: bridge